### ISSUE TITLE
Need more information in Readme

### ISSUE THREAD

**Issue by anuragkumar95** [airavata-courses/codestorm#20]
The installation instructions are very vague. Please put clear instructions and links to referenced project documentation (eg, links to docker documentation ), so the user, who might not know about docker, spring-boot, flask... can still install and run your application.

**Comment by drishti2497** [comment]
All right working on it, thanks for the feedback @anuragkumar95

**Comment by DakshaNagre** [comment]
Link to install confluent kafka
https://docs.confluent.io/current/quickstart/ce-docker-quickstart.html#ce-docker-quickstart
