### ISSUE TITLE
Create MongoDb cluster for User Management

### ISSUE THREAD

**Issue by DakshaNagre** [airavata-courses/codestorm#5]
@drishti2497 
Create MongoDb cluster for User Management

**Comment by drishti2497** [comment]
mongodb://drishti2497:<password>@userdata-shard-00-00-ilngl.mongodb.net:27017,userdata-shard-00-01-ilngl.mongodb.net:27017,userdata-shard-00-02-ilngl.mongodb.net:27017/test?replicaSet=UserData-shard-0&ssl=true&authSource=admin
